/**
 * Server-side authentication utility
 * Generates and verifies time-based HMAC signatures
 */

/**
 * Server-side authentication utility
 * Generates and verifies time-based HMAC signatures
 * Compatible with Edge Runtime (Web Crypto API)
 */

const SECRET_KEY = process.env.SECRET_KEY || 'flashtransfer-default-dev-secret-key-32chars';
const TIMESTAMP_WINDOW_MS = 2 * 60 * 1000; // 2 minutes

async function getKey(): Promise<CryptoKey> {
    const encoder = new TextEncoder();
    const keyData = encoder.encode(SECRET_KEY);
    return await crypto.subtle.importKey(
        'raw',
        keyData,
        { name: 'HMAC', hash: 'SHA-256' },
        false,
        ['sign', 'verify']
    );
}

function bufferToHex(buffer: ArrayBuffer): string {
    return Array.from(new Uint8Array(buffer))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');
}

function hexToBuffer(hex: string): Uint8Array {
    if (hex.length % 2 !== 0) throw new Error('Invalid hex string');
    const buffer = new Uint8Array(hex.length / 2);
    for (let i = 0; i < hex.length; i += 2) {
        buffer[i / 2] = parseInt(hex.substring(i, i + 2), 16);
    }
    return buffer;
}

/**
 * Generate HMAC signature for timestamp
 * SERVER-SIDE ONLY
 */
export async function generateToken(): Promise<{ token: string; timestamp: number }> {
    const timestamp = Date.now();
    const encoder = new TextEncoder();
    const data = encoder.encode(timestamp.toString());
    const key = await getKey();

    const signature = await crypto.subtle.sign(
        'HMAC',
        key,
        data
    );

    return {
        token: bufferToHex(signature),
        timestamp
    };
}

/**
 * Verify token was generated by us and is within time window
 * SERVER-SIDE ONLY
 */
export async function verifyToken(token: string, timestamp: number): Promise<boolean> {
    if (!token || !timestamp || !SECRET_KEY) {
        return false;
    }

    try {
        // Check timestamp is within acceptable window
        const now = Date.now();
        const timeDiff = Math.abs(now - timestamp);

        if (timeDiff > TIMESTAMP_WINDOW_MS) {
            console.warn(`Token expired: time diff ${Math.floor(timeDiff / 1000)}s (max 120s)`);
            return false;
        }

        const encoder = new TextEncoder();
        const data = encoder.encode(timestamp.toString());
        const key = await getKey();

        const isValid = await crypto.subtle.verify(
            'HMAC',
            key,
            hexToBuffer(token) as unknown as BufferSource,
            data
        );

        return isValid;
    } catch (error) {
        console.error('Token verification error:', error);
        return false;
    }
}
